### ISSUE TITLE
How can i custom the textarea

### ISSUE THREAD

**Issue by nncuong1311** [GrumpyWizards/wizMarkdown#5]
Please show me how can i custom the textarea with ng-model, and another attribute when i use editor or textarea only.

**Comment by gaetancollaud** [comment]
I added the possibility to customize classes of the textarea in the pullrequest #7. If you don't want to wait for the pull request, you can use the bower package _gaetancollaud-wiz-markdown_.

```
bower install --save gaetancollaud-wiz-markdown
```
