### ISSUE TITLE
How can I generate a TOC?

### ISSUE THREAD

**Issue by yqt** [GrumpyWizards/wizMarkdown#6]

**Comment by gregorypratt** [comment]
# Table of Contents
    1. [Example](#example)
    2. [Example2](#example2)

    ## Example
    ## Example2

Would produce:
# Table of Contents
1. [Example](#example)
2. [Example2](#example2)

## Example
## Example2

**Comment by yqt** [comment]
Maybe adding a `feature` like using *[TOC]* to generate the table of content automatically is not a bad idea?

**Comment by gregorypratt** [comment]
This directive set is just a wrapper for MarkdownDeep but you could augment the text to auto generate a toc but it would be quite a bit of work...happy to review and accept pull requests ;-)

**Comment by vroudge** [comment]
@gregorypratt pretty good idea! might do it one of these days if I have time on my hands
